Główne zadanie domowe skończone
TomaszAndrzejPawlowski/goit-nodejs-hw-02 pull request #4
Opened 2024-02-26 20:16 UTC by TomaszAndrzejPawlowski

Proszę o sprawdzenie zadania.
Próbowałem zrobić dodatkowe zadanie, ale na razie nie rozumiem jak korzystać z Jest'a. 
Jeszcze na pewno będę próbował jak znajdę czas, ale oddaję pracę główną i tak już po czasie.

2024-02-27 16:32 UTC, KamilMr requested changes
Hej, 
Kilka poprawek napisanych w pull request, jak by coś było niejasne to pisz na slaku. 
I stwórz sobie osobny moduł do update pliku jak znajdziesz czas. :)

2024-02-27 16:32 UTC, KamilMr commented on models/users.js
> +let extOfSavedFile = "";
Tutaj wydaje się że jest to niepotrzebne przetrzymywanie w file scope tych zmiennych.

2024-02-27 16:32 UTC, KamilMr commented on models/users.js
> +const UPLOAD_DIRECTORY = path.join("public", "avatars", nameOfSavedFile);
nameOfSavedFile to jest plik z tego co widzę, a stała sugeruje że jest to folder.

2024-02-27 16:32 UTC, KamilMr commented on models/users.js
> +    const user = await User.findOne({ token: body.token });
Token powinien przyjść w header i być tam odczytany. Ta ścieżka jeśli potrzebuje uzytkonika powinna być authorized.

2024-02-27 16:32 UTC, KamilMr commented on models/users.js
> +      await Jimp.read("tmp/incognitoman.png").then(function (img) {
incognitoman.png 
To powinno być robione dynamicznie a nie statycznie (hard coded). Czyli kiedy ja dodaję obrazek on zostaje umieszczony w folderze tmp pod jakąś nazwą. Następnie w jimp powinienem dać mu ścieżkę do pliku tego w tmp. Zobacz sobie co posiada req.file.

2024-02-27 16:32 UTC, KamilMr commented on models/users.js
> +    const user = await User.findOne({ token: body.token });
User powinien być pobrany przez auth i być dostępny w `req.user`

2024-02-27 16:32 UTC, KamilMr commented on tmp/IncognitoMan-oryginalSize.png
Pod koniec procesu zapisu obrazka tmp powinien być pusty a avatar zapisany w directory public/avatars

2024-02-27 18:37 UTC, TomaszAndrzejPawlowski commented on models/users.js
> +let extOfSavedFile = "";
Faktycznie przy aktualnej opcji nadawania nazwy plikom nie jest to potrzebne.

Najpierw napisałem kod do tworzenia nazwy z Date.now() , wtedy potrzebowałem tych dwóch zmiennych, ponieważ jeśli używałem funkcji do tworzenia nazwy wielokrotnie to nazwa obrazka różniła się odrobinkę o jedną albo dwie ostatnie cyfry. Dlatego potrzebowałem tych zmiennych, aby użyć funkcji tylko raz przy utworzeniu pliku, a potem móc używać kilkukrotnie w różnych miejscach utworzonej nazwy.

Usunąłem te zmienne i całą funkcję, ponieważ wystarczy mi teraz tylko file.originalname , używam Jimp'a do resize'a i nadaję właściwą nazwę avatara, a potem usuwam z tmp pierwotny obrazek.

2024-02-27 18:37 UTC, TomaszAndrzejPawlowski commented on models/users.js
> +const UPLOAD_DIRECTORY = path.join("public", "avatars", nameOfSavedFile);
Usunąłem nameOfSavedFile.

2024-02-27 18:37 UTC, TomaszAndrzejPawlowski commented on models/users.js
> +    const user = await User.findOne({ token: body.token });
Tutaj używałem tokena do znalezienia użytkownika, zmieniłem na _id: req.user._id .
Funkcja auth w router.patch("/avatars", auth,[...]  działa poprawnie, jak nie podam tokena w Auth w postmanie to wyrzuca 401 "Not authorized".

2024-02-27 18:37 UTC, TomaszAndrzejPawlowski commented on models/users.js
> +      await Jimp.read("tmp/incognitoman.png").then(function (img) {
Poprawiłem, miałem to zmienić ale zostawiłem przez przypadek.

2024-02-27 18:37 UTC, TomaszAndrzejPawlowski commented on tmp/IncognitoMan-oryginalSize.png
Dodałem usuwanie z folderu tmp.

2024-02-28 16:19 UTC, KamilMr approved these changes
Hej,
Zadanie wygląda spoko :-) 
Powodzenia!

2024-02-28 16:27 UTC, merged